wip
taigaio/taiga-back pull request #1540
Opened 2020-12-09 19:04 UTC by yamila-moreno

![](https://media.giphy.com/media/3KVcFEmdDl9NYaFTtx/giphy.gif)

2020-12-28 16:12 UTC, bameda requested changes

2020-12-28 16:12 UTC, bameda commented on taiga/telemetry/services.py
> +        ).count(),
The `,` at the end of this line generate a tuple (a list in the json request sent to the telemetry service)

2020-12-28 16:12 UTC, bameda commented on taiga/telemetry/services.py
> +        ).count()
Same here

2020-12-28 16:12 UTC, bameda commented on taiga/telemetry/services.py
> +    pd['tt_users'] = User.objects.count()
add `excludes(is_system=True)` to exclude system users (like github, gitlab... integration users)

2020-12-28 16:20 UTC, yamila-moreno commented on taiga/telemetry/services.py
> +
fixed!

2020-12-28 16:20 UTC, yamila-moreno commented on taiga/telemetry/services.py
> +        ).count(),
fixed!

2020-12-28 16:21 UTC, yamila-moreno commented on taiga/telemetry/services.py
> +        ).count()
you mean the comma? or something different?

2020-12-28 16:22 UTC, yamila-moreno commented on taiga/telemetry/services.py
> +    pd['tt_users'] = User.objects.count()
fixed!

2020-12-28 16:30 UTC, bameda commented on taiga/telemetry/services.py
> +        ).count()
No, I'd use ` excludes(is_system=True)` here too.

2020-12-28 16:42 UTC, yamila-moreno commented on taiga/telemetry/services.py
> +        ).count()
fixed!

2020-12-28 16:48 UTC, bameda approved these changes

2020-12-29 16:19 UTC, merged

2020-12-29 16:19 UTC, bameda commented
![](https://thumbs.gfycat.com/FairGrandBlackwidowspider-size_restricted.gif)