[wip] New taiga.auth module
taigaio/taiga-back pull request #30
Opened 2021-07-02 15:09 UTC by bameda

2021-07-14 10:57 UTC, yamila-moreno requested changes, later dismissed
This review includes some typos.

2021-07-14 10:57 UTC, yamila-moreno commented on settings/common.py
> +    'FLUSH_REFRESHED_TOKENS_PERIODICITY': 3 * 24 * 3600, # secons
typo > "seconds"

2021-07-14 10:57 UTC, yamila-moreno commented on taiga/auth/settings.py
> +      'FLUSH_REFRESHED_TOKENS_PERIODICITY': 3 * 24 * 3600, # secons
typo > "seconds"

2021-07-14 10:57 UTC, yamila-moreno commented on taiga/auth/settings.py
> +    'FLUSH_REFRESHED_TOKENS_PERIODICITY': 3 * 24 * 3600, # secons
typo > "seconds"

2021-07-14 10:57 UTC, yamila-moreno commented on CHANGELOG.md
> +- New Auth module, based on djangorestframework-simplejwt (history #tg-4625, issue #tgg-626))
typos
- history > story
- tgg-626 > tg-626

2021-07-14 10:57 UTC, yamila-moreno commented on taiga/auth/compat.py
> +            "is deprecated. Remove the parentheses to use it as an attribute.",
typo parenthesis

2021-07-27 11:22 UTC, tdelatorre approved these changes

2021-07-27 14:43 UTC, yamila-moreno approved these changes

2021-07-27 14:47 UTC, merged