WIP: Us/4616/research date cancel user
taigaio/taiga-back pull request #31
Opened 2021-07-06 12:06 UTC by tdelatorre

2021-07-08 07:10 UTC, yamila-moreno requested changes

2021-07-08 07:10 UTC, yamila-moreno commented on tests/integration/test_users.py
> +    date_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day)
these could be `date_now = datetime.date.today()`

2021-07-08 07:10 UTC, yamila-moreno commented on tests/integration/test_users.py
> +    date_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day)
these could be `date_now = datetime.date.today()`

2021-07-08 10:24 UTC, tdelatorre commented on tests/integration/test_users.py
> +    date_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day)
Done!

2021-07-08 10:24 UTC, tdelatorre commented on tests/integration/test_users.py
> +    date_now = datetime.datetime(datetime_now.year, datetime_now.month, datetime_now.day)
Done!

2021-07-09 08:51 UTC, yamila-moreno approved these changes

2021-07-12 08:38 UTC, merged